### ISSUE TITLE
格式转换

### ISSUE THREAD

**Issue by ywgrit** [zweix123/jyyslide-md#12]
谢谢你的工具，请问有办法将生成的html转换为pdf吗？

**Comment by zweix123** [comment]
![image](https://github.com/user-attachments/assets/a3703320-0996-445f-81e8-1d7daf024768)

截图中的链接: https://revealjs.com/pdf-export/ , 按照revealjs的手册操作即可.

+ 注意: 
   + 手册中的操作有在网址添加 `?print-pdf` , 注意这里使用的是`8000/?print-pdf`, 即没有`#`.
   + 最终的效果, pdf是"横版"的, 即样式和通过浏览器浏览的效果是一摸一样的, 假如发生了变形, 说明操作有误.

**Comment by ywgrit** [comment]
> ![image](https://private-user-images.githubusercontent.com/74446314/367137603-a3703320-0996-445f-81e8-1d7daf024768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTM2MzYsIm5iZiI6MTcyNjIxMzMzNiwicGF0aCI6Ii83NDQ0NjMxNC8zNjcxMzc2MDMtYTM3MDMzMjAtMDk5Ni00NDVmLTgxZTgtMWQ3ZGFmMDI0NzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA3NDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzAwY2EyMDAyYWNjNjIxZGI0ZmEwZjM5Y2NjZjlkNTg1ZGNiYjM3YzE1ZTk0OWQwMDA1YTU2N2Q4YjNlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FzaesUTbufhM7GuCh4sd8ocPyLbmR-j90cw80MKg6EM)
> 
> 截图中的链接: https://revealjs.com/pdf-export/ , 按照revealjs的手册操作即可.
> 
> * 注意:
>   
>   * 手册中的操作有在网址添加 `?print-pdf` , 注意这里使用的是`8000/?print-pdf`, 即没有`#`.
>   * 最终的效果, pdf是"横版"的, 即样式和通过浏览器浏览的效果是一摸一样的, 假如发生了变形, 说明操作有误.

非常感谢，不好意思没仔细看你写的说明
