### ISSUE TITLE
bug : encoding error in windows11

### ISSUE THREAD

**Issue by Nateiru** [zweix123/jyyslide-md#2]
在windows下可能出现编码问题，如果按照 **控制面板 -> 区域 -> 管理 -> 更改系统区域设置 -> 打开Beta版** 的方式解决，貌似可能导致其他软件的字符显示出现问题？

**Comment by zweix123** [comment]
我这里的设置是在win10上的，我个人没有遇到问题（我没有用过win11）。
您可以不采用这个设置，如果没有这样设置也没有编码问题就不用设置啦。

**Comment by zweix123** [comment]
关于编码的问题的发现者来自[Jungle](https://github.com/Jungle430)，他的机器就是win11。

**Comment by Nateiru** [comment]
感谢回复，此办法确实能解决字符乱码的问题，但可能导致一些软件乱码，需要注意一下（本地有一个很老版本的软件出现乱码），具体的详见知乎对该问题的讨论 [在 Windows11 中是否应该勾选Beta版：使用 Unicode UTF-8 提供全球语言支持？](https://www.zhihu.com/question/536400200)
