### ISSUE TITLE
bug : The chardet library does not recognize the encoding format of the text file containing the emojis

### ISSUE THREAD

**Issue by Nateiru** [zweix123/jyyslide-md#3]
本人在Windows11测试 `操作系统概述.md` 的过程中，发现由于该md文件中有一个表情“😂”，导致在`file_util.py`中的 `def get_file_code(filepath: str) -> str` 返回值得到 None，此时可能出现一些问题。

原因是：**chardet库并不能识别包含Emoji表情符号的文本文件的编码格式。**

**Comment by zweix123** [comment]
您会发现样例中复刻了蒋老师幻灯片的测试Markdown文件就包含这个表情，但是它的转换是没有问题的。  
但是当MarkDown文件只有这个表情时，在我的机器上（win10，开启语言Beta版），则会出现乱码。

chardet这个库的算法基于[这篇论文](https://www-archive.mozilla.org/projects/intl/universalcharsetdetection)，其返回的是一个可能的结果，即结果会被样本量所影响。

在普通的Markdown文件中，函数`get_file_code`会返回`None`（即使这样，它确实正确的解码了，我并不清楚这样的情况win下的Python会如何处理），但是当文件中只有一个Emoji表情符号时，则返回`windows-1251`，观测结果这样会对Emoji解码错误。

我对这个函数进行了修改，将其结果限定在几种可能中，应该可以解决这个问题。

感谢您的关注。
