### ISSUE TITLE
关于行间公式不是衬线字体

### ISSUE THREAD

**Issue by lovelxc** [zweix123/jyyslide-md#5]
使用$$写公式不是衬线字体，看着很难受，有没有办法修复呢

**Comment by zweix123** [comment]
请问您说的“不是衬线字体”是什么意思？

如果您的意思是转换不支持数学公式，那么是可能您的语法有问题

比如下面的代码

```markdown
$$
1 \times 2
$$

$1 \times 2$
```

效果如下
![image](https://github.com/zweix123/jyyslide-md/assets/74446314/a09f4015-bbaa-47ce-95a9-6a243b6caef9)


如果您的意思是对转换后的数学公式字体不满意，您可以做自己的定制化

同样是上面的那份代码，转换后的HTML代码为
```html
    <div class="reveal">
        <div class="slides">
            <section>
                <section>
                    <div>
                        <p class="font-serif my-1">$$
                            1 \times 2
                            $$</p>
                        <p class="font-serif my-1">$1 \times 2$</p>
                    </div>
                </section>
            </section>
        </div>
    </div>
```

我们发现数学公式内容并没有做转换，仍然是LaTeX源码，所以转变应该是Reveal提供的功能，而这里涉及的类名都没有出现在蒋老师自己的CSS文件中，即都是Reveal自己的类，个人认为这部分定制难度较大。如果您很感兴趣可能需要去研究下Reveal。

**Comment by zweix123** [comment]
请问您能给出Bug复现的Markdown文本嘛？
