### ISSUE TITLE
语法高亮失效

### ISSUE THREAD

**Issue by trace1729** [zweix123/jyyslide-md#8]
环境是 manjaro Linux. 运行 poetry run python main.py xx 构建后，代码段没有高亮。
代码段使用的语法是  (\`\`\`  \`\`\`)

**Comment by zweix123** [comment]
1. 确定Markdown代码块语法是否生效，jyyslide-md要的的Markdown语法应该是最严格的语法，代码块应该使用前后有空行的，分为两行的```，这样的代码块才会有代码高亮，如果希望代码在其他文字中，即使用不换行的两个`包围起来，这样的代码不支持高亮。
2. 代码高亮由第三方库`pygments`提供，可**在poetry环境下**使用`pip list 2>/dev/null | grep 'pygments'`检查是否有该库。

**Comment by trace1729** [comment]
感谢回复，已解决。

记录如下：

- 尝试使用 `poetry shell` 进入虚拟环境，终端接收到 -1 的返回值，没有任何输出。

- 由于我一开始用的是 `pacman -S python-poetry` 安装的 poetry, 怀疑是系统更新的时候，poetry 的环境被污染了。

- 之后我尝试使用 venv 创建一个虚拟环境，再使用虚拟环境安装 `poetry`。安装成功后，构建出来的 slide 有 语法高亮了。
